version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - test:
          name: test_node6
          v: "6"
      - test:
          name: test_node8
          v: "8"
      - test:
          name: test_node12
          v: "12"
      - test:
          name: test_node14
          v: "14"
      - test:
          name: test_node16
          v: "16"
jobs:
  test:
    parameters:
      v:
        type: string
        default: "6"
    docker:
      - image: circleci/node:<< parameters.v >>
    environment:
      LANG: en_US.UTF-8
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}
            - npm-packages-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          name: Save NPM Package Cache
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Tests
          command: npm run test
